### ISSUE TITLE
Infinite Sliding Issue

### ISSUE THREAD

**Issue by sachin-nikamNeo** [rcaferati/react-awesome-slider#10]
Hi @rcaferati 
Not able to reuse the prop to stop the infinite sliding functionality. I need to stop any further right-swiping from the last page, and same with any further left-swiping from the first page.
Tried utilizing the **infinite** _prop_, but unable to make it behave as expected.

**Comment by rcaferati** [comment]
Hey @sachin-nikamNeo thanks for pointing it out. I've double checked it here and everything seems to be working as expected.

Just use something like: 
```
<AwesomeSlider infinite={false}>
  <div>1</div>
  <div>2</div>
  <div>3</div>
  <div>4</div>
 </AwesomeSlider>
```
