### ISSUE TITLE
Images getting cropped

### ISSUE THREAD

**Issue by Tsabary** [rcaferati/react-awesome-slider#101]
I can't seem to find any issue on the topic, or anything explaining how to deal with it.

I am using the slider for simple images, all sized 1600 by 1200.
All images seem to be zoomed in a bit, cropping their edges by maybe like 10%.

This is how I am using the library:

```
      <AwesomeSlider
        infinite
        media={[
          {
            source: "/imgs/ui/dribbble1.png"
          },
          {
            source: "/imgs/ui/dribbble2.png"
          },
          {
            source: "/imgs/ui/dribbble3.png"
          },
          {
            source: "/imgs/ui/dribbble4.png"
          },
          {
            source: "/imgs/ui/dribbble5.png"
          }
        ]}
      />
```

And here is a sample of the same image originally, and in the slider:

![Screenshot (350)](https://user-images.githubusercontent.com/47200891/74638875-7427a480-5175-11ea-866d-1b8f84590400.png)

![Screenshot (351)](https://user-images.githubusercontent.com/47200891/74638914-8275c080-5175-11ea-86db-defa064d11d0.png)

**Comment by rcaferati** [comment]
Hey @Tsabary. The slider uses by default `object-fit: cover;` on the image that's rendered via `source`. You can add your own image via children of each slider's `div` or you can change the `--slider-height-percentage` via `css` or `js` to fit the 1600x1200 (75%) proportion. Then it will render it correctly.

**Comment by Tsabary** [comment]
Hey @rcaferati  apologies, but I can't seem to get it to work. Would you be abe to show me how to adjust what I am doing now so it would?

Currently this is how I'd set the divs:

```
        <AwesomeSlider infinite>
          {/* {renderImages()} */}
          <div className="ui-image__container">
            <img
              src={"/imgs/ui/dribbble1.png"}
              className="ui-image"
            />
          </div>
          <div className="ui-image__container">
            <img
              src={"/imgs/ui/dribbble2.png"}
              className="ui-image"
            />
          </div>

        </AwesomeSlider>
```


And these are my css properties:

```
.ui-image {
    display: block;
    object-fit: contain;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    margin: auto;
    &__container {
      position: relative;
      text-align: center;
    }
  }
```

I am still getting everything as before

**Comment by chhz1** [comment]
I am not sure if you still need an answer but I thought it might help someone else looking for help.
What the dev suggests you is to use the `--slider-height-percentage` with 75%. 75% of 1600px equals 1200px. Your code could look like this:
`
<AutoplaySlider
...
style={{
        "--slider-height-percentage": "75%"
      }}
...
/>
`

This matches the aspect ratio of your image.

This is not a good idea if you have multiple images with different aspect ratios.
Object-fit should be an accessible option!
