### ISSUE TITLE
video, iframe not supported

### ISSUE THREAD

**Issue by muscaiu** [rcaferati/react-awesome-slider#102]
Is video or iframe supported by the library?

For some reason i'm not able to load any video

[CodeSandbox ](https://codesandbox.io/s/quiet-bird-p2h46?fontsize=14&hidenavigation=1&theme=dark)

```
import React from "react";
import AwesomeSlider from "react-awesome-slider";
import "react-awesome-slider/dist/styles.css";

export default function App() {
  return (
    <AwesomeSlider>
      <video>
        <source
          src={
            "https:....mp4"
          }
          type="video/mp4"
        />
      </video>
      <div data-src={"https://placekitten.com/200/300"} />
    </AwesomeSlider>
  );
}

```

**Comment by rcaferati** [comment]
Hey @muscaiu. Just wrap the `<video>` on a `<div>` container.

Check it out on this [codesandbox](https://codesandbox.io/s/awesome-slider-basic-video-m9j9s) example.
