### ISSUE TITLE
React-awesome-slider from navbar menu to route and switch between the slides

### ISSUE THREAD

**Issue by HHKP1** [rcaferati/react-awesome-slider#107]
### Hi guys. Need help with a router and switch. I use awesome-react-slider and when I use the switch, only one slide is rendered, but eight are needed. I am trying to use navigation from the navbar menu to navigate between slides. What ideas. Many thanks.

`import React from 'react';
import {Switch, Route} from 'react-router-dom';
import CupThree from "./CupThree.jsx";
import CupTwo from "./CupTwo.jsx";
import SlideSeven from "./slide_7.jsx";
import SlideSix from "./slide_6.jsx";
import SlideFive from "./slide_5.jsx";
import SlideFour from "./slide_4.jsx";
import SlideThree from "./slide_3.jsx";
import Cup from "./Cup.jsx";
import Slider from 'react-awesome-slider';
import 'react-awesome-slider/dist/styles.css';
import s from './stylesSlide.module.css';
import SlideTwo from "./slide_2.jsx";

class SSlider extends React.Component {

	render() {

		const sT = {
			className: "",
			speed: 1500,
			dots: true,
			startup: true,
			startupScreen: true,
			infinite: true,
			slidesToShow: 1,
			slidesToScroll: 1,
			adaptiveHeight: true,
			scrollable: true,
			draggable: true,
			resizable: true,
		};

		return (

			<Slider {...sT}
				// startupScreen={startupScreen}
				    cssModule={s}>
				<Switch>
					<Route exact path="/" render={() => <Cup/>}/>
					<Route path="/cupTwo" render={() => <CupTwo/>}/>
					<Route path="/cupThree" render={() => <CupThree/>}/>
					<Route path="/slideTwo" render={() => <SlideTwo/>}/>
					<Route path="/slideThree" render={() => <SlideThree/>}/>
					<Route path="/slideFour" render={() => <SlideFour/>}/>
					<Route path="/slideFive" render={() => <SlideFive/>}/>
					<Route path="/slideSix" render={() => <SlideSix/>}/>
					<Route path="/slideSeven" render={() => <SlideSeven/>}/>
				</Switch>
			</Slider>

		)
	}
}

export default SSlider;
`

**Comment by rcaferati** [comment]
Hey @HHKP1! Have you looked into the [**Navigation HOC Strategy**](https://github.com/rcaferati/ras-fullpage-strategies)? There's a conceptual example and a demo using NextJS.

**Comment by HHKP1** [comment]
this is exactly what i need. Thanks a lot. You are a genius
