### ISSUE TITLE
Selected prop not updating position in the bullets

### ISSUE THREAD

**Issue by Diegolotr99** [rcaferati/react-awesome-slider#12]
I am initializing my AwesomeSlider with an specific position...But the bullets below does not show that position, so when I start navigating is always at the first...
Example:
<AwesomeSlider
         selected=3 //To show the 4th media from the list at creation..
         infinite={false} >
        {mediaItems} //this are my media items source list..
</AwesomeSlider>

In the bullets of navigation it does not show the correct index, the one passed in the selected prop.

**Comment by rcaferati** [comment]
Hey @Diegolotr99 thanks for pointing it out. It's fixed from version `0.7.0`. If you have any further problems just reopen it here o/
