### ISSUE TITLE
set responsive image css custom?

### ISSUE THREAD

**Issue by PokerJava** [rcaferati/react-awesome-slider#146]
i use --slider-height-percentage 25% ,  image not  not working responsive.

**Comment by trolit** [comment]
Hi @PokerJava. If by "not working responsive" you mean that it doesn't fit slider properly, you didn't configure styles.scss for react-awesome-slider. You probably have in your styles.scss

```scss
// Note: below code starts at line 101 in default file
> img,
> video {
  object-fit: cover;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
```

Let's refer to [w3schools](https://www.w3schools.com/cssref/css3_pr_object-fit.asp) docs about object-fit ```cover``` attribute:

> The replaced content is sized to maintain its aspect ratio while 
filling the element's entire content box. The object will be **clipped** to fit


Check [this site's slider](https://trolit.github.io/EzGitDoc-documentation/)

If this is the behaviour you expect from react-awesome slider refer to latest issue [here](https://github.com/rcaferati/react-awesome-slider/issues/147#issuecomment-706706461)

**Comment by chhz1** [comment]
You might wanna look at #147
