### ISSUE TITLE
I can't get my images

### ISSUE THREAD

**Issue by akelesis** [rcaferati/react-awesome-slider#16]
Hi, I'm having some problem with the path to my images. In my src folder I have a folder for images and other folder for components, I'm trying to get my images from a component like this:
`<div data-src="../assets/imgs/slider/img-0.png"/>` but it's not working, Am I doing anything wrong?

**Comment by rcaferati** [comment]
@akelesis you should use the publicly available path for the image. You could be using the path for it inside the project.
