### ISSUE TITLE
Autoplay works only after click 

### ISSUE THREAD

**Issue by lanadedstudio** [rcaferati/react-awesome-slider#160]
I implemented this plugin in my project, but the autoplay works only after click in the arrows. I would like the slider to start automatically.

This is my script:
                        <AutoplaySlider
                            play={true}
                            cancelOnInteraction={false} // should stop playing on user interaction
                            interval={6000}
                            organicArrows={false}
                            bullets={false}>

**Comment by trolit** [comment]
Hi @lanadedstudio. Code sample you've provided looks OK. Please make sure that you:

1) Added following imports to the component
```javascript
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
```

2) Instantiated AutoplaySlider in your component like this
```javascript
const AutoplaySlider = withAutoplay(AwesomeSlider);
```

**Comment by lanadedstudio** [comment]
sorry, I already put these lines in the code, but it doesn't work. The slide starts only after clicking the arrows.

**Comment by lanadedstudio** [comment]
I find my error! In Class Components, this line:

`const AutoplaySlider = withAutoplay(AwesomeSlider);`

must be inside the render() method, I had put it outside...

**Comment by trolit** [comment]
Good job! 👍 To be honest I have this declaration outside function in js component and it's working fine 😄 

```
const AutoplaySlider = withAutoplay(AwesomeSlider);

function Home() {
 return (
    <Layout
       <AutoplaySlider
                 play={true}
                 cancelOnInteraction={false} // should stop playing on user interaction
                 interval={6}
                 <...>
    </Layout>
 );
}
```

**Comment by trolit** [comment]
Don't forget to close the issue if you've solved it =)
