### ISSUE TITLE
Captions not working

### ISSUE THREAD

**Issue by Irungaray** [rcaferati/react-awesome-slider#165]
`import withCaption from 'react-awesome-slider/dist/captioned';`

The file which the above sentence tries to import doesnt exist.

So when you compile, it throws an error. I tried searching for older versions but I still didnt find the file for that route.

Hope you can fix it!

**Comment by trolit** [comment]
You can get captioned.js from the example (click <a href="https://github.com/rcaferati/react-awesome-slider/blob/master/demo/examples/example/captioned.js">here</a>) :)

**Comment by Irungaray** [comment]
Hey, thank you so much! I already managed to do it without that file, but i'll implement it.

**Comment by hanu7674** [comment]
> Hey, thank you so much! I already managed to do it without that file, but i'll implement it.

Can you please tell us, how did you do that. Especially hoc components like autoplay, captioned-images without using babel.
