### ISSUE TITLE
Autoplay HOC error

### ISSUE THREAD

**Issue by santiperone** [rcaferati/react-awesome-slider#169]
I'm getting this error on console when using Autplay HOC:

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: AwesomeSlider

**Comment by arinconc** [comment]
I've get the same error. Any suggestion?

Thank you!
