### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by shakediel** [rcaferati/react-awesome-slider#18]
hey there,
I'm trying to use react-awesome-sloder with create-react-app
on the first try after installation i get the following error:

`Support for the experimental syntax 'classProperties' isn't currently enabled
`

i dont want to eject so i was wondering if there is anything you may do on your end

thank in advance!

**Comment by rcaferati** [comment]
@shakediel actually there is. From version `0.8.0` I'm pointing `main` to the `dist` folder. From this version on you should be good using it directly into a `CRA` project.
