### ISSUE TITLE
slide in components not getting rendered

### ISSUE THREAD

**Issue by zilahir** [rcaferati/react-awesome-slider#25]
So, i don't know if its a bug, or i am missing something. 

I have the following code: 

```
<AwesomeSlider
						cssModule={AwsSliderStyles}
						bullets={false}
						infinite={false}
						fillParent
					>
						{
							slides.map(currentSlide => (
								<Slide slide={currentSlide} />
							))
						}</AwesomeSlider>
```

and the `Slide` component looks the following: 

```
const Slide = (props) => {
	const { slide } = props
	return (
		<div style={{ backgroundImage: `url(${slide.bgImage})`, backgroundSize: 'contain', backgroundRepeat: 'no-repeat', backgroundPosition: '50% 50%' }} />
	)
}
```

pretty simple, but it's not working. 

However, if i copy that single `div` from the `Slide` component, and place it directly in the `map`, it works. 

Do you have any idea what might the problem be?

**Comment by Paulbarrios** [comment]
Same problem

**Comment by AmitTurner** [comment]
I haven't tried it yet, but sometimes it only accept Array type objects as children, meaning you have to create one from the map function or use another function and not map (its weird but i encountered it in similar packages.

**Comment by zilahir** [comment]
thank you!
