### ISSUE TITLE
[Request?] --startup class on container element

### ISSUE THREAD

**Issue by UriellViana** [rcaferati/react-awesome-slider#28]
I'm trying to conditionally style the controls on the startup slide and the _startUp is only applied on the slide content element.

If the container had a class like `aws-sld--startup` we could do something similar to the `--first` and `--last` classes where the left or right control isn't visible.

My current workaround was using the `className` prop on AwesomeSlider to make it work since I'm always using a startup slide.

**Comment by rcaferati** [comment]
Just set the `infinite` prop to false and it will not render the initial and final arrows. If you have any further issues just let me know :)
