### ISSUE TITLE
[Bug] Startup node skips first slide when advancing

### ISSUE THREAD

**Issue by UriellViana** [rcaferati/react-awesome-slider#29]
https://github.com/rcaferati/react-awesome-slider/blob/master/src/core/index.js#L84

This seems to be due to index going from null to 1 (instead of going to 0).

Workaround is to have an useless slide element as the first slide, but then you can still navigate back into it 😦

I assumed it's a bug, correct me if I'm wrong

**Comment by leeseean** [comment]
https://codesandbox.io/s/lingering-dream-vein7

**Comment by rcaferati** [comment]
Hey @UriellViana, all fixed on v2.0.0. Thank you 🙌🏻
