### ISSUE TITLE
Prop for set hidden arrow when at first or last page.

### ISSUE THREAD

**Issue by huynguyen-n** [rcaferati/react-awesome-slider#3]
Hi bro,

I using this library and I looking for a props to set hidden arrow button like your portfolio page. Can you shown me which is props or we need add this to your library, tell me you suggestion and we will go through on that.

Thanks

**Comment by rcaferati** [comment]
Hey @huynguyen-n, thanks for the feedback. This is interesting. It's currently animating the slides in an infinite fashion. I'll add a prop to set it to a linear behaviour -- therefore hiding the initial and final arrows.

**Comment by huynguyen-n** [comment]
Thanks bro!
