### ISSUE TITLE
Local blob image not rendering

### ISSUE THREAD

**Issue by davidpene** [rcaferati/react-awesome-slider#30]
Can we change [this line](https://github.com/rcaferati/react-awesome-slider/blob/2a44c6a93976385ceec9df807b4103a3f0e18b10/src/core/media.js#L18) so that it's the default behaviour?
i.e `if (media.url.match(/mp4/)) ... else { background = <img... }`

I have an input that accepts images, I then use those files to `URL.createObjectUrl(file)` and pass it to the AwesomeSlider.

**Comment by rcaferati** [comment]
Hey @davidpene, thanks for letting me know. I've done just that, from v1.2.0 on it's rendering the image tag by default
