### ISSUE TITLE
Problems with touch in the responsive version.

### ISSUE THREAD

**Issue by jzambrano12** [rcaferati/react-awesome-slider#32]
The library works well when it is in desktop version, but when I switch to mobile version and change the image with the touch I skip the error that I will show you next.
![Selección_071](https://user-images.githubusercontent.com/27393245/62956335-605f4800-bdb8-11e9-9e73-dfa0e3d8cbe1.png)
![Selección_072](https://user-images.githubusercontent.com/27393245/62956343-62c1a200-bdb8-11e9-82ca-09ec0f8af50d.png)

Any suggestions on what to do to fix this?

**Comment by rcaferati** [comment]
Hey @jzambrano12. If you're still into this one, can you show me the code that's generating the slider? I couldn't figure it just by the above error.

**Comment by leeseean** [comment]
https://codesandbox.io/s/lingering-dream-vein7

**Comment by code2080** [comment]
I have same issue if I set organicArrows = false. I must edit css to set opacity of arrow class = 0 to hide arrows.
