### ISSUE TITLE
autoplay hoc has wrong import and 

### ISSUE THREAD

**Issue by AmitTurner** [rcaferati/react-awesome-slider#42]
Using the AutoPlay hoc example from your website, I get the following error:
![Code_MghdlojmDQ](https://user-images.githubusercontent.com/19940028/66958452-dc079a80-f070-11e9-9e32-31c6876935a5.png)

apparently the dir is wrong, so ive added '/src' to that line. now it finds the file but i get a different error:
![Code_Hfw2preLae](https://user-images.githubusercontent.com/19940028/66958717-77990b00-f071-11e9-8f0e-4f11462a12f5.png)
Ive used the old version with no problems so i think i dont misuse it now.

the old way someone posted here for auto-play crashes on mobile when users move too many pictures fast so ive decided to move to your new version! hopefully it will work soon thank you for this package!

**Comment by rcaferati** [comment]
Hey @AmitTurner! Thanks for raising it. I've done a small path fix on `v2.0.1`. Just update it and open this again if you have any issues.

**Comment by AmitTurner** [comment]
thank you for your reply,
the example showed in your portfolio doesnt work,
im getting the second error. is the use of hoc different in anyway? 
ive done hoc before without any problems.

**Comment by milind2945** [comment]
@rcaferati any updates?
I have the same issue.
