### ISSUE TITLE
Fatal error when is served in production

### ISSUE THREAD

**Issue by fernan256a** [rcaferati/react-awesome-slider#46]
Hello guys,

I started using react-awesome-slider just a few days ago, easy to use and worked great in my local env, after all my tests I compiled (npm run build) to deploy it in production and boom nothing works. After all my debugging I realized that only importing your library my component never loads... The error:

Uncaught TypeError: Super expression must either be null or a function, not undefined
    at index.js:950
    at index.js:949
    at Object.e.exports (index.js:926)
    at n (index.js:14)
    at Object.e.exports (index.js:205)
    at n (index.js:14)
    at Object.e.exports (index.js:166)
    at n (index.js:14)
    at Object.e.exports (index.js:158)
    at n (index.js:14)

I even tried with a clean (new) project and the result is always the same

The error:
![image](https://user-images.githubusercontent.com/56699397/67099601-e2d30200-f183-11e9-9d5d-57b1eabb092e.png)

My clean project with the import:
![image](https://user-images.githubusercontent.com/56699397/67099656-fe3e0d00-f183-11e9-8e72-742a0be47b45.png)

**Comment by rcaferati** [comment]
Hey @fernan256a! What are you using for building it?

**Comment by fernan256a** [comment]
@rcaferati I'm using **npm run build**

**Comment by rcaferati** [comment]
Have you started your project using `create-react-app`?

**Comment by 4asof4ik** [comment]
the same issue: Next.js and deploy to Heroku

**Comment by rcaferati** [comment]
@4asof4ik Does the error occur locally when you run `yarn build`?

**Comment by fernan256a** [comment]
Ey guys,

It was hard but after several hours I finally could solve it... I had to eject your project and start to modify configurations, without minify everything works fine. So, I imported the "src" and when I compiled the error jumped again.

I realize that you're using something that is in experimental stage in ecma6, so I found that the new react-app includes a plugin to work with that, then I updated it and DONE, everything starts working great again.

**Comment by fernan256a** [comment]
To complement my answer a bit more... now I'm using:

react-scripts:3.2.0
babel/core:7.6.0

**Comment by 4asof4ik** [comment]
> @4asof4ik Does the error occur locally when you run `yarn build`?
> 
> When I create a clean Next.js installation and add the package. It builds, exports and loads normally.

build run good but start crash

**Comment by rcaferati** [comment]
@fernan256a @4asof4ik guys I've done a bit of a webpack build review and released on `v2.2.0`, you can check that out. If the error persists please just link me to a repository reproducing it.
