### ISSUE TITLE
Image fullscreen on click

### ISSUE THREAD

**Issue by JairAviles** [rcaferati/react-awesome-slider#5]
What about including functionality that when clicking the image, it shows it fullscreen, click again and return to normal state?

**Comment by fabdelgado** [comment]
Its possible add video to slider and pause while autoplay video?

**Comment by rcaferati** [comment]
Hey @JairAviles. You can use the `fillParent` prop to achieve a fullScreen functionality. The slider will expand to the limits of the parent container. Just make sure that the parent is filling the whole screen.
