### ISSUE TITLE
How can I get this to work without a background?

### ISSUE THREAD

**Issue by cbr9** [rcaferati/react-awesome-slider#54]
I'm trying to use this for a text slider that goes over the background of a different div. However, if I remove the default background, you can see the previous element. Is there some workaround for this?

(I know it's probably not possible, but I wanted to ask nonetheless)

**Comment by rcaferati** [comment]
Hey @cbr9! Thanks for raising it. You’re right, overlapping content between sliders is not possible on the current structure. Can you show me a reference?

**Comment by cbr9** [comment]
Sure thing.
![Screenshot_20191110_092743](https://user-images.githubusercontent.com/46726554/68541162-673c2d80-039c-11ea-96b6-789678265f66.png)
![Screenshot_20191110_092747](https://user-images.githubusercontent.com/46726554/68541163-673c2d80-039c-11ea-9bf1-1495dc7943f3.png)
It's a web app for a heave metal band. When you click on the next or previous button of the media player, the text on the top changes. Right now I'm just updating the innerText, but I'd like to animate it. That text has a background that simply darkens the record image (which goes underneath). I kind of found a solution, but it still wasn't perfect (setting the record image as the background of every slide, but then the record image moves).

**Comment by rcaferati** [comment]
@cbr9 Nice! I was reviewing it and actually after the change from css transitions to animations we were having this unwanted flash behaviour underneath the visible box.

I've fixed it on `v2.2.1`. Now you would be able to use a fixed background without problems.

**Comment by cbr9** [comment]
> @cbr9 Nice! I was reviewing it and actually after the change from css transitions to animations we were having this unwanted flash behaviour underneath the visible box.
> 
> I've fixed it on `v2.2.1`. Now you would be able to use a fixed background without problems.

Thank you so much!!
