### ISSUE TITLE
Cant show images

### ISSUE THREAD

**Issue by akayee** [rcaferati/react-awesome-slider#55]
![image](https://user-images.githubusercontent.com/53110296/68545553-34ffef80-03df-11ea-9765-66f4f63084a1.png)

import AwesomeSlider from 'react-awesome-slider';
import AwesomeSliderStyles from 'react-awesome-slider/src/styled/fold-out-animation';

 <AwesomeSlider cssModule={AwesomeSliderStyles}>
              <div data-src="./assets/img/federico-beccari.jpg" />
              <div data-src="./assets/img/daniel-olahs.jpg" />
              <div data-src="./assets/img/netherlandculture.jpg" />
            </AwesomeSlider>

result empty. Dunnow why?

**Comment by rcaferati** [comment]
Hi @akayee, thanks for raising it. You're importing it correctly. Can you show me how are you implementing the slider itself?

**Comment by akayee** [comment]
<AwesomeSlider cssModule={AwesomeSliderStyles}>
              <div data-src="./assets/img/federico-beccari.jpg" />
              <div data-src="./assets/img/daniel-olahs.jpg" />
              <div data-src="./assets/img/netherlandculture.jpg" />
            </AwesomeSlider>


hello i actually wrote it too but github didint show

**Comment by rcaferati** [comment]
@akayee it's probably something related to the source. Have you tried removing the `./` and using just `assets/img/file-name.jpg`?

**Comment by akayee** [comment]
i did but nothing change i also did src/assets...

**Comment by rcaferati** [comment]
@akayee What are you using as project base? `react-create-app`, `next.js`, `gatsby.js`?

**Comment by akayee** [comment]
I am using Paperkit 2 Demo (Material kit) Reactstrap

**Comment by tareefdev** [comment]
I have the same problem, all HTML elements seems loaded correctly with its CSS rules, but images don't appear. I'm using Gatsby.
You could see the slider here:
http://betasyrianarchive.tk/
Also the source code is there:
https://gitlab.com/tareefdev/sy-beta/blob/master/src/pages/index.js#L40

**Comment by tareefdev** [comment]
Inspecting the HTML shows that images are available too:
![Screenshot_20191217_134146](https://user-images.githubusercontent.com/17391433/70988556-2342f380-20d3-11ea-9aba-5598890cac09.png)

**Comment by tareefdev** [comment]
I found that the first slide doesn't take `awssld--active` class, so it's invisible, adding it to the first slide makes its image be appeared but other slider functionalities don't work, for example, pressing on arrows doesn't slide images

**Comment by rcaferati** [comment]
Which version are you using @tareefdev?

**Comment by tareefdev** [comment]
I use the version 2.2.1
 https://gitlab.com/tareefdev/sy-beta/blob/master/package.json#L58

**Comment by tareefdev** [comment]
Updating to 2.3.0 solves the issue.

**Comment by rcaferati** [comment]
@tareefdev Awesome!
