### ISSUE TITLE
back and next "buttons" missing aria label 

### ISSUE THREAD

**Issue by AmitTurner** [rcaferati/react-awesome-slider#59]
According to all page tests and accessibility tests, all Buttons must have discernible text.
meaning, adding 
`aria-label="back"`
and 
`aria-label="next"`
to the arrow buttons will help across all devices and give a better score for search crawlers.
Just my two cents. thanks for the package! amazing work.

**Comment by rcaferati** [comment]
Hey @AmitTurner thanks for raising it. I've added it on `v2.4.0`.
