### ISSUE TITLE
How can I use touch enabled ?

### ISSUE THREAD

**Issue by rainstormza** [rcaferati/react-awesome-slider#6]
Do you have any example code ?

![image](https://user-images.githubusercontent.com/4003032/41243667-f1f97fe8-6dcc-11e8-949a-ea40d7b80562.png)

thanks

**Comment by rcaferati** [comment]
Hey @rainstormza. Touch enabled is the default behaviour on mobile.

**Comment by nghiadang-vizion** [comment]
how can I touch anabled on desktop?

> Hey @rainstormza. Touch enabled is the default behaviour on mobile.
