### ISSUE TITLE
override arrow component

### ISSUE THREAD

**Issue by kkesley** [rcaferati/react-awesome-slider#60]
Can we override organic arrow component via the props?

This is very useful if we want custom arrows.

**Comment by rcaferati** [comment]
Hey @kkesley, thanks for raising it.

I've added this to `v2.4.0` you can use `buttonContentRight` or `buttonContentLeft` to add custom content to the buttons. You can also disable them setting `buttons = false` and overwrite the navigation with a `customContent` component.
