### ISSUE TITLE
in production TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by topovik** [rcaferati/react-awesome-slider#61]
Hi, nice slider, good job

There is a problem, in dev environment:

`ƒ t(e){!function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}(this,t);var n=function(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() h…`

but slider work, and in the production environment:

`TypeError: Super expression must either be null or a function, not undefined`

and slider not work
i use next.js, i tried ssr: false, dynamic import when componentDidMount...

**Comment by rcaferati** [comment]
Hey @topovik, thanks for raising it. This is fixed on `v2.2.2`.
