### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by rmarquardt1** [rcaferati/react-awesome-slider#65]
After running a build and deploying into my prodution environment, I receive the following error:

TypeError: Super expression must either be null or a function, not undefined

Everything works fine in my dev environment. It seems to be stemming from the code shown in the screenshot located in dist\index.js and/or dist\autoplay.js.

Any idea how I can get around this? Thanks.
![error](https://user-images.githubusercontent.com/52170882/70868742-94f33400-1f51-11ea-9a2a-b3a8484c4f14.PNG)
![ConsoleError](https://user-images.githubusercontent.com/52170882/70868757-d5eb4880-1f51-11ea-91d1-8db8e564ebaa.PNG)

**Comment by rcaferati** [comment]
Hey @rmarquardt1, thanks for raising it. Which version are you in?

**Comment by rmarquardt1** [comment]
Thanks for the quick response. I'm using version 2.2.1.

**Comment by rcaferati** [comment]
@rmarquardt1 Try `2.3.0` out. This bug should be fixed. Let me know if everything worked fine.

**Comment by rmarquardt1** [comment]
That fixed it. Thanks! I have another issue but I'll open it up as  a new issue. Thanks again!
