### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by bensbits91** [rcaferati/react-awesome-slider#71]
Works perfectly in dev. When I try to build, it can't minify. I think it's because dist/index.js is already minified, but not sure. I tried using src/index.js, but can't parse, "... may need an appropriate loader...". 

I have a dozen other modules working. Only react-awesome-slider causes issue. I can run in dev with our without react-awesome-slider. When I try to build, get error. Can build and run in production WITHOUT react-awesome-slider.

Am I trying to import incorrectly? Any other ideas?

Thanks!
Ben

**Comment by rcaferati** [comment]
Hey @bensbits91, thanks for raising it. Which version are you on?

**Comment by bensbits91** [comment]
Hi @rcaferati, I was using 2.2.0. I just updated to 2.4.0. It seems to be working in dev and production now. Thanks for your response.
