### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Jackc415** [rcaferati/react-awesome-slider#76]
Even following the most basic example, it's still not functioning at all. The arrows are missing, the bullets won't transition to the other slides, etc. The only thing that this is doing is showing the first picture I have and nothing else.

```
import AwesomeSlider from 'react-awesome-slider';
import 'react-awesome-slider/dist/styles.css';

const slider = (
      <AwesomeSlider
        fillParent={true}
      >
        <div data-src="https://images.befunky.com/wp/wp-2014-08-milky-way-1023340_1280.jpg?auto=format&fm=jpg&q=75&w=1776&ixlib=js-1.4.1" />
        <div data-src="https://images.befunky.com/wp/wp-2015-11-hellofall4.jpg?auto=format&fm=jpg&q=75&w=1248&ixlib=js-1.4.1"/>
      </AwesomeSlider>
    );

```

**Comment by rcaferati** [comment]
Hi @Jackc415, thanks for raising it. Apologies for the annoying bug I'm just putting 3.0 up and this one slipped through. Checkout `v3.0.5` the bug should be fixed.

If you wanna check out the new full-page navigation HOC just go to [fullpage.caferati.me](https://fullpage.caferati.me) all feedback is really appreciated.
