### ISSUE TITLE
programatically trigger navigation

### ISSUE THREAD

**Issue by ajit-hi** [rcaferati/react-awesome-slider#80]
how can i programatically trigger next or previous buttons.

**Comment by rcaferati** [comment]
Hi @ajit-hi, thanks for raising it. Have you tried controlling the currently selected slide?

In the example bellow, if you change the selected variable it'll trigger the animation to the newly selected slide.

```jsx
import AwesomeSlider from 'react-awesome-slider';
import 'react-awesome-slider/dist/styles.css';

const slider = () => {
    const [selected, setSelected] = useState(0)

    // ...

    return (
      <AwesomeSlider selected={selected}>
        <div>1</div>
        <div>2</div>
        <div>2</div>
      </AwesomeSlider>
    );
}
```

**Comment by ajit-hi** [comment]
Hi, I tried controlling the selected slide but it did not work. 
Thanks.

**Comment by rcaferati** [comment]
@ajit-hi can you show me a snippet of the code?

**Comment by ajit-hi** [comment]
HI, I want to pause slider for some second and the restart it. Pause on start of a video. and play again on end of the video. I m trying this code but this is not working.

import React, { useState, useEffect } from 'react'
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import 'react-awesome-slider/dist/styles.css';

const AutoplaySlider = withAutoplay(AwesomeSlider);


const contents = [
    {
        type: 'image',
        url : 'forza.jpg'
    },
    {
        type: 'image',
        url : 'supercars.jpg'
    },
    {
        type : 'video',
        url : 'random.mp4'
    }
]

const Slider = () =>  {

    const [ play, setPlay ] = useState(true)
   
    alert(play ? 'True' : 'False')

    useEffect(() => {
        setTimeout(() => {
           setPlay(false) 
        }, 8000);

        setTimeout(() => {
            setPlay(true)
        }, 20000)
    },[])

    return (<div>
        <AutoplaySlider
            play={play}
            cancelOnInteraction={false} // should stop playing on user interaction
            interval={6000}
        >
                {
                contents.map((item,index) => {
                    switch(item.type){
                        case 'image':
                            return <div data-src={item.url} key={index+'image'}/>
                        case 'video':
                            // return (
                            //     <div key={index+'video-div'}>
                            //         <video
                            //         key = {index + 'video'}
                            //         autoPlay="autoplay" 
                            //         preload = "auto"
                            //         style={{maxHeight:'99.99vh'}}
                            //         muted={true}
                            //         onPlay = {() => {
                            //             setPlay(false)
                            //         }}
                            //         onEnded = {() => {
                            //             setPlay(true)
                            //         }}
                            //         >
                            //             <source src={item.url} />
                            //         </video>
                            //     </div>

                            // )
                        default:
                            return <div data-src="toadvertise_image.png"/>
                    }
                })
            }
        </AutoplaySlider>
    </div>
    )}



export default Slider

**Comment by rcaferati** [comment]
Hey @ajit-hi. Just update it to `v4.0.1` and try it again. It should work.

**Comment by ajit-hi** [comment]
`import React, { Component } from 'react';
import AwesomeSlider from 'react-awesome-slider'
import withAutoPlay from 'react-awesome-slider/dist/autoplay'
import 'react-awesome-slider/dist/styles.css'


const AutoPlaySlider = withAutoPlay(AwesomeSlider)


class AdSlider extends Component {
    state = { 
        autoPlay:true,
     }


    render() {



        let delay = this.state.delay
        if(this.props.inTransit){
            delay = delay + 500
        }

        return ( 
            <React.Fragment>
                
                <AutoPlaySlider 
                play={this.state.autoPlay}
                interval={6000}
                cancelOnInteraction={false}
                transitionDelay={delay}
                animation="foldOutAnimation"
                buttons = {true}
                bullets = {false}
                fillParent = {true}
                >
                    {
                    this.props.urls.map((item,index) => {
                        switch(item.type){
                            case 'image':
                                return <div data-src={item.url} key={index+'image'}/>
                            case 'video':
                                return (
                                    <div key={index+'video-div'}>
                                        <video
                                        key = {index + 'video'}
                                        autoPlay="autoplay" 
                                        preload = "auto"
                                        style={{maxHeight:'99.99vh'}}
                                        muted={true}
                                        onPlay = {(e) => {
                                            this.setState({autoPlay : false})
                                            setTimeout(() => {
                                                this.setState({autoPlay: true})
                                            },e.target.duration * 1000)
                                        }}
                                        >
                                            <source src={item.url} />
                                        </video>
                                    </div>

                                )
                            default:
                                return <div data-src="toadvertise_image.png"/>
                        }
                    })
                }
                </AutoPlaySlider>
            </React.Fragment>
         );
    }
}


export default AdSlider;`

**Comment by ajit-hi** [comment]
I m using above code and its not working. I did upgrade to version 4.0.1 as you said. Thanks for your help. I m setting autoplay to false on video start and then, setting a timeout to start  autoplay again but its not working. Although if i click on one of the arrows, autoplay again starts playing.
