### ISSUE TITLE
Autoplay/Captioned HOC not working

### ISSUE THREAD

**Issue by cbr9** [rcaferati/react-awesome-slider#89]
I'm trying to create a carousel with captioned images. When I run yarn start, this happens:

Failed to compile.
./node_modules/react-awesome-slider/src/hoc/autoplay/index.js
SyntaxError: /home/cabero/Code/Go/src/github.com/cbr9/southgate/client/node_modules/react-awesome-slider/src/hoc/autoplay/index.js: Unexpected token (8:9)

   6 | 
   7 | export default function(props) {
>  8 |   return <AutoplayComponent transitionDelay={100} {...props} />;
     |          ^
   9 | }
  10 | 
import AutoplaySlider from 'react-awesome-slider/hoc/autoplay';

This happens when I try to import HOCs from the hoc folder. Since there is a version of Autoplay outside of this, I can make autoplay work, but I can't get captioned images to work. Is there any workaround?
I am using TypeScript 3.7.5.

**Comment by rcaferati** [comment]
Hey @cbr9, thanks for raising it. I've done a bit of a refactor of the autoplay HOC on `v3.2.2`, please check that out. Also you an you take a look at #86 which has a discussion regarding it.

**Comment by cbr9** [comment]
Still can't get it to work. My original idea was to make an autoplay-captioned slider. I still get the unexpected token problem. Also if I import the styles and use them on the autoplay component, they just don't apply. How could this be achieved?

**Comment by rcaferati** [comment]
@cbr9 I wasn't thinking of a double composition. Although the CaptionedHOC isn't publicly exported I've done a bit of testing and it should work normally with the double composition.

Can you show me the basis of your implementation?

**Comment by cbr9** [comment]
I tried wrapping the autoplay component with the captioned component, and viceversa, but I keep getting the unexpected token error.

`
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import CaptionedComponent from 'react-awesome-slider/src/hoc/captioned-images/index';

const AutoplaySlider = withAutoplay(CaptionedComponent(AwesomeSlider));

const Carousel = () => {
	return (
		<PictureCarouselWrapper>
			<AutoplaySlider fillParent={true} play={true} infinite={true} interval={5000} organicArrows={false} bullets={true}>
				<div data-src={'/client/src/assets/img/gallery/alberto-min.jpg'}>
					<p>Alberto Gil Hernandez</p>
				</div>
				<div data-src={'/client/src/assets/img/gallery/diego-min.jpg'}>
					<p>Diego Chozas Cano</p>
				</div>
			</AutoplaySlider>
		</PictureCarouselWrapper>
	);
};`

**Comment by rcaferati** [comment]
Hey @cbr9. Just update to the latest version `v4.0.2` and follow the HOC example. It should work fine.

```
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import withCaption from 'react-awesome-slider/dist/captioned';

const AutoplaySlider = withAutoplay(withCaption(AwesomeSlider));
```

**Comment by bfencing98** [comment]
Hello @rcaferati, I'm looking for the exact same feature as @cbr9 but when I try your thing, it ends with an exception because captioned.js doesn't exist in react-awesome-slider/dist/..., only captioned.css does.
I tried to download the file from github and put it manually in dist/ but I get this error:  
SyntaxError: D:\Users\Utilisateur\Documents\Projet iSim\iSim\client\node_modules\react-awesome-slider\dist\captioned.js: Unexpected token (87:2)

  85 | 
  86 | const startupScreen = (
> 87 |   <div style={{ backgroundColor: '#85d4b9' }}>
     |   ^
  88 |     <img
  89 |       style={{ width: '20%' }}
  90 |       alt="Rick and Morty Loader"

Did I miss something in the way to do it?
