### ISSUE TITLE
props play

### ISSUE THREAD

**Issue by rep74joao** [rcaferati/react-awesome-slider#96]
Rafael boa tarde, parabens pelo slider eh show de bola.

Se colocar o play={true} ele da um erro "Uncaught TypeError: Cannot read property 'appendChild' of null" se tirar funciona normalmente mais eh interessante ele iniciar automático

**Comment by rcaferati** [comment]
Boa @rep74joao! I've published a fix on `v4.0.2`. The error was actually happening when you'd set `play={true}` and the slider component had no rendered children. It should be all good now, thanks 🙌🏻

**Comment by rep74joao** [comment]
maravilha atualizei aqui deu certinho forte abx
